version: 2.1

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy
          command: ${SERVER_CONNECTION_COMMAND} 'source ~/.nvm/nvm.sh; cd /var/www/builds/docs/; git pull origin master; yarn; yarn build'
      - run:
          name: Release
          command: ${SERVER_CONNECTION_COMMAND} 'cp -r /var/www/builds/docs/. /var/www/docs'
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:  
                - master
                